# Generated by Django 5.1.3 on 2024-11-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secretária',
            new_name='Enfermeira',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='id_secretaria',
            new_name='id_enfermeira',
        ),
    ]
