# Generated by Django 5.1.3 on 2024-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_paciente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
