# Generated by Django 5.1.1 on 2024-11-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_secretária_enfermeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sintoma',
            field=models.CharField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(
                fields=('cpf',), name='unique_paciente_cpf'),
        ),
    ]
