# Generated by Django 5.1.3 on 2024-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_consulta_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(default='dor'),
            preserve_default=False,
        ),
    ]
